### ISSUE TITLE
Pico Remotes wont respond until indicator light (tx) turns off

### ISSUE THREAD

**Issue by mspace00** [upsert/lutron-caseta-pro#20]
I'm not quite sure where the problem lies here (I can only assume me) but whenever I try to trigger an automation with the sensor.pico in hassio it takes two seconds to fire. I can confirm the automation will fire immediately when the green light on the pico stops flashing. If I keep pressing the button on the pico (to keep the light flashing) the automation will not fire until I stop and then the light stops. 
I had assumed that hassio was not seeing the state change until the light stopped flashing, however testing the button presses while watching the sensor in hassio shows immediate state changes. I'm stumped.
Here is my automation code:
```
- id: '1548110829104'
  alias: Dining Room Pico On
  trigger:
  - entity_id: sensor.pico_remotes_dining_room_pico
    platform: state
    to: '1'
  action:
    entity_id: light.dining_room_main_lights
    service: light.turn_on
```
Running HA 84.3 and my lutron app reports 6.3
