### ISSUE TITLE
Multiple Smart Bridges Pro

### ISSUE THREAD

**Issue by oleggold** [upsert/lutron-caseta-pro#36]
What is a proper way to configure multiple smart bridges pro?

**Comment by upsert** [comment]
You can repeat the -host part in the configuration. Like this:
```yaml
lutron_caseta_pro:
    bridges:
      - host: IP_ADDRESS
        mac: MAC_ADDRESS
      - host: IP_ADDRESS_2
        mac: MAC_ADDRESS_2
```

Where IP_ADDRESS_2 and MAC_ADDRESS_2 are the IP address and MAC address respectively of your second bridge.
